#测试环境配置
#保存图片的目录
upload-path: /usr/local/file/
server:
  port: 8080 #服务端口配置
  contextPath: /my
spring:
#提供热部署功能
  thymeleaf:
      cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,file:${upload-path}
  datasource:
    url: jdbc:mysql://169.254.99.206:3306/csair_eshop?serverTimezone=UTC&characterEncoding=utf-8&useSSL=true
    username: root
    password: admin
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  #freemarker配置
  freemarker:
    allow-request-override: false
    cache: false #关闭缓存，便与调试。在生产环境中???
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    settings:
      number_format: 0.########
      template_update_delay: 0